add_newline = false

[aws]
disabled = true

[directory]
style = "green"

[character]
style_success = "green"

[git_branch]
style = "bold green"
truncation_length = 32

[git_state]
style = "magenta"

[git_status]
style = "yellow"
format = '([\($all_status$ahead_behind\)]($style) )'

[time]
disabled = false
format = "%R"

[package]
disabled = true
