add_newline = false

[aws]
disabled = true

[directory]
style = "green"

[character]
success_symbol = "[❯](bold green)"

[git_branch]
style = "bold green"
truncation_length = 32

[git_state]
style = "magenta"

[git_status]
style = "yellow"
format = '([\($all_status$ahead_behind\)]($style) )'

[time]
disabled = false
time_format = "%R"
format = "[$time]($style) "

[package]
disabled = true
